package com.sophiecheese.alloys.datagen;

import com.sophiecheese.alloys.SophiesAlloys;
import com.sophiecheese.alloys.init.BlockInit;
import com.sophiecheese.alloys.util.AlloysTags;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.BlockTags;
import net.minecraft.world.level.block.Blocks;
import net.neoforged.neoforge.common.Tags;
import net.neoforged.neoforge.common.data.BlockTagsProvider;
import net.neoforged.neoforge.common.data.ExistingFileHelper;
import org.jetbrains.annotations.Nullable;

import java.util.concurrent.CompletableFuture;

public class AlloysBlockTagProvider extends BlockTagsProvider {
	public AlloysBlockTagProvider(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider, @Nullable ExistingFileHelper existingFileHelper) {
		super(output, lookupProvider, SophiesAlloys.MOD_ID, existingFileHelper);
	}

	@Override
	protected void addTags(HolderLookup.Provider provider) {
	//Vanilla Tags
		tag(BlockTags.MINEABLE_WITH_PICKAXE)
			.addTag(AlloysTags.Blocks.SOUL_STONE_ALL_BLOCK)
			.addTag(AlloysTags.Blocks.BLACKSTONE_ALL_BLOCK)
			.addTag(AlloysTags.Blocks.CALCITE_ALL_BLOCK)
			.addTag(AlloysTags.Blocks.SLATE_ALL_BLOCK)
			.addTag(AlloysTags.Blocks.DIORITE_ALL_BLOCK)
			.addTag(AlloysTags.Blocks.GRANITE_ALL_BLOCK)
			.addTag(AlloysTags.Blocks.MOSSY_DEEPSLATE_ALL_BLOCK)
			.addTag(AlloysTags.Blocks.SMELTED_STORAGE_BLOCK)
			.addTag(AlloysTags.Blocks.RAW_STORAGE_BLOCK)
			.addTag(AlloysTags.Blocks.SOPHIE_ORES_BLOCK)
			.addTag(AlloysTags.Blocks.DUSTY_LAMPS_BLOCK)
			.addTag(AlloysTags.Blocks.LEADED_QUARTZ_GLASS_BLOCK)
			.addTag(AlloysTags.Blocks.LEADED_QUARTZ_GLASS_PANES_BLOCK)
			.add(BlockInit.RICH_BASALT.get())
			.add(BlockInit.ROUGH_SLATE.get())
			//.add(BlockInit.COBBLE_CRAFTING_TABLE.get())
			;
		tag(BlockTags.MINEABLE_WITH_SHOVEL)
			.add(BlockInit.ROUGH_SLATE.get())
			.add(BlockInit.BLACK_GRAVEL.get())
			.add(BlockInit.BLACK_SAND.get())
			.add(BlockInit.SOUL_GRAVEL.get())
			.add(BlockInit.DEEP_GRAVEL.get())
			.add(BlockInit.DEEP_SAND.get())
			.add(BlockInit.LEADED_QUARTZ_SAND.get());
		tag(BlockTags.MINEABLE_WITH_HOE)
			.add(BlockInit.MEAT_BLOCK.get())
			.add(BlockInit.OREBERRY_CRATE.get());

		tag(BlockTags.NEEDS_DIAMOND_TOOL)
			.add(BlockInit.NETHER_MITHRIL_ORE.get())
			.add(BlockInit.BASALT_MITHRIL_ORE.get())
			.add(BlockInit.TUNGSTEN_ORE.get())
			.add(BlockInit.DEEPSLATE_TUNGSTEN_ORE.get())
			.add(BlockInit.RAW_TUNGSTEN_BLOCK.get())
			.add(BlockInit.TUNGSTEN_BLOCK.get());
		tag(BlockTags.NEEDS_IRON_TOOL)
			.add(BlockInit.ELECTRUM_ORE.get())
			.add(BlockInit.DEEPSLATE_ELECTRUM_ORE.get())
			.add(BlockInit.FOXITE_ORE.get())
			.add(BlockInit.DEEPSLATE_FOXITE_ORE.get())
			.add(BlockInit.RAW_FOXITE_BLOCK.get())
			.add(BlockInit.FOXITE_BLOCK.get())
			.add(BlockInit.TRITONIUM_ORE.get())
			.add(BlockInit.DEEPSLATE_TRITONIUM_ORE.get())
			.add(BlockInit.TRITONIUM_BLOCK.get())
			.add(BlockInit.RAW_TRITONIUM_BLOCK.get())
			.add(BlockInit.JADE_ORE.get())
			.add(BlockInit.DEEPSLATE_JADE_ORE.get())
			.add(BlockInit.JADE_BLOCK.get())
			.add(BlockInit.RAW_ELECTRUM_BLOCK.get())
			.add(BlockInit.ELECTRUM_BLOCK.get())
			.add(BlockInit.STEEL_BLOCK.get())
			.add(BlockInit.OBERITE_BLOCK.get())
			.add(BlockInit.LYCALITE_BLOCK.get())
			.add(BlockInit.BABULYMN_BLOCK.get())
			.add(BlockInit.SOUL_MEAT_ORE.get())
			.add(BlockInit.SOUL_MITHRIL_ORE.get())
			.add(BlockInit.RAW_MITHRIL_BLOCK.get())
			.add(BlockInit.MITHRIL_BLOCK.get());
		tag(BlockTags.NEEDS_STONE_TOOL)
			.add(BlockInit.LEAD_ORE.get())
			.add(BlockInit.DEEPSLATE_LEAD_ORE.get())
			.add(BlockInit.QUINGUM_ORE.get())
			.add(BlockInit.DEEPSLATE_QUINGUM_ORE.get())
			.add(BlockInit.QUINGUM_BLOCK.get())
			.add(BlockInit.CRIMSON_COAL_ORE.get())
			.add(BlockInit.CRIMSON_COAL_BLOCK.get())
			.add(BlockInit.SILVER_ORE.get())
			.add(BlockInit.DEEPSLATE_SILVER_ORE.get())
			.add(BlockInit.SILVER_BLOCK.get())
			.add(BlockInit.RAW_SILVER_BLOCK.get())
			.add(BlockInit.NETHER_FOXITE_ORE.get())
			.add(BlockInit.MEAT_ORE.get())
			.add(BlockInit.DEEPSLATE_MEAT_ORE.get())
			.add(BlockInit.NETHER_MEAT_ORE.get())
			.add(BlockInit.END_MEAT_ORE.get())
			.add(BlockInit.SOUL_FOXITE_ORE.get())
			.add(BlockInit.DEEP_GRAVEL.get())
			.addTag(AlloysTags.Blocks.SLATE_ALL_BLOCK);

		tag(BlockTags.BASE_STONE_NETHER)
			.add(BlockInit.SOUL_COBBLESTONE.get())
			.add(BlockInit.SOUL_STONE.get());
		tag(BlockTags.BASE_STONE_OVERWORLD)
			.add(BlockInit.ROUGH_SLATE.get())
			.add(BlockInit.SLATE.get());
		tag(BlockTags.NETHER_CARVER_REPLACEABLES)
			.add(BlockInit.SOUL_STONE.get())
			.add(BlockInit.SOUL_COBBLESTONE.get())
			.add(BlockInit.SOUL_GRAVEL.get())
			.add(BlockInit.BLACK_SAND.get())
			.add(BlockInit.BLACK_GRAVEL.get());
		tag(BlockTags.STONE_ORE_REPLACEABLES)
			.add(BlockInit.ROUGH_SLATE.get());
		tag(BlockTags.DEEPSLATE_ORE_REPLACEABLES)
			.add(BlockInit.SLATE.get())
			.add(BlockInit.DEEP_GRAVEL.get());



		tag(BlockTags.SAND)
			.add(BlockInit.DEEP_SAND.get())
			.add(BlockInit.BLACK_SAND.get());

		tag(BlockTags.SCULK_REPLACEABLE)
			.add(BlockInit.ROUGH_SLATE.get())
			.add(BlockInit.SLATE.get())
			.addTag(AlloysTags.Blocks.MOSSY_DEEPSLATE_ALL_BLOCK);
		tag(BlockTags.SCULK_REPLACEABLE_WORLD_GEN)
			.add(BlockInit.ROUGH_SLATE.get())
			.add(BlockInit.SLATE.get())
			.addTag(AlloysTags.Blocks.MOSSY_DEEPSLATE_ALL_BLOCK);
		tag(BlockTags.MOSS_REPLACEABLE)
			.add(BlockInit.ROUGH_SLATE.get())
			.add(BlockInit.SLATE.get())
			.add(BlockInit.DEEP_GRAVEL.get())
			.add(BlockInit.MOSSY_COBBLED_DEEPSLATE.get());
		tag(BlockTags.LUSH_GROUND_REPLACEABLE)
			.add(BlockInit.ROUGH_SLATE.get())
			.add(BlockInit.SLATE.get())
			.add(BlockInit.DEEP_GRAVEL.get())
			.add(BlockInit.MOSSY_COBBLED_DEEPSLATE.get());
		tag(BlockTags.INFINIBURN_NETHER)
			.addTag(AlloysTags.Blocks.SOUL_STONE_ALL_BLOCK)
			.add(BlockInit.SOUL_MEAT_ORE.get())
			.add(BlockInit.CRIMSON_COAL_BLOCK.get());
		tag(BlockTags.INFINIBURN_OVERWORLD)
			.addTag(AlloysTags.Blocks.SOUL_STONE_ALL_BLOCK)
			.add(BlockInit.CRIMSON_COAL_BLOCK.get());
		tag(BlockTags.SOUL_SPEED_BLOCKS)
			.add(BlockInit.SOUL_GRAVEL.get())
			.addTag(AlloysTags.Blocks.SOUL_STONE_ALL_BLOCK);
		tag(BlockTags.SOUL_FIRE_BASE_BLOCKS)
			.add(BlockInit.SOUL_STONE.get())
			.add(BlockInit.SOUL_COBBLESTONE.get())
			.add(BlockInit.SOUL_GRAVEL.get())
			.add(BlockInit.SOUL_MEAT_ORE.get())
			.addTag(AlloysTags.Blocks.SOUL_STONE_ALL_BLOCK);

		tag(BlockTags.WITHER_IMMUNE)
			.add(BlockInit.TUNGSTEN_BLOCK.get())
			.add(BlockInit.RAW_TUNGSTEN_BLOCK.get());

		tag(BlockTags.WALLS)
			.add(BlockInit.SLATE_WALL.get())
			.add(BlockInit.SLATE_BRICK_WALL.get())
			.add(BlockInit.SLATE_TILE_WALL.get())
			.add(BlockInit.SLATE_WALL.get())
			.add(BlockInit.SOUL_STONE_WALL.get())
			.add(BlockInit.SOUL_STONE_BRICK_WALL.get())
			.add(BlockInit.SOUL_STONE_TILES_WALL.get())
			.add(BlockInit.SOUL_COBBLESTONE_WALL.get())
			.add(BlockInit.COBBLED_GRANITE_WALL.get())
			.add(BlockInit.COBBLED_BLACKSTONE_WALL.get())
			.add(BlockInit.COBBLED_DIORITE_WALL.get())
			.add(BlockInit.COBBLED_CALCITE_WALL.get())
			.add(BlockInit.MOSSY_COBBLED_DEEPSLATE_WALL.get())
			.add(BlockInit.MOSSY_DEEPSLATE_BRICK_WALL.get());

		tag(BlockTags.BEACON_BASE_BLOCKS)
			.add(BlockInit.BABULYMN_BLOCK.get())
			.add(BlockInit.ELECTRUM_BLOCK.get())
			.add(BlockInit.FOXITE_BLOCK.get())
			.add(BlockInit.JADE_BLOCK.get())
			.add(BlockInit.LAGOMITE_BLOCK.get())
			.add(BlockInit.LYCALITE_BLOCK.get())
			.add(BlockInit.OBERITE_BLOCK.get())
			.add(BlockInit.SILVER_BLOCK.get())
			.add(BlockInit.TRITONIUM_BLOCK.get())
			.add(BlockInit.TUNGSTEN_BLOCK.get());
		tag(BlockTags.BEE_GROWABLES)
			.add(BlockInit.OREBERRY_BUSH_BLOCK.get());
		tag(BlockTags.GUARDED_BY_PIGLINS)
			.addTag(AlloysTags.Blocks.C_ORES_ELECTRUM_BLOCK)
			.addTag(AlloysTags.Blocks.C_ORES_FOXITE_BLOCK)
			.addTag(AlloysTags.Blocks.C_ORES_MITHRIL_BLOCK)
			.add(BlockInit.FOXITE_BLOCK.get())
			.add(BlockInit.ELECTRUM_BLOCK.get())
			.add(BlockInit.MITHRIL_BLOCK.get())
			.add(BlockInit.RICH_BASALT.get());
		tag(BlockTags.PIGLIN_REPELLENTS)
			.addTag(AlloysTags.Blocks.C_SOUL_LANTERNS_BLOCK);
		tag(BlockTags.IMPERMEABLE)
			.addTag(AlloysTags.Blocks.LEADED_QUARTZ_GLASS_BLOCK)
			.addTag(AlloysTags.Blocks.STAINED_LEADED_QUARTZ_GLASS_BLOCK);

	//Common Tags
		tag(Tags.Blocks.GRAVELS)
			.add(BlockInit.SOUL_GRAVEL.get())
			.add(BlockInit.DEEP_GRAVEL.get())
			.add(BlockInit.BLACK_GRAVEL.get());
		tag(Tags.Blocks.NEEDS_NETHERITE_TOOL)
			.add(BlockInit.BLACKSTONE_MITHRIL_ORE.get())
			.add(BlockInit.END_TUNGSTEN_ORE.get())
			.add(BlockInit.END_LAGOMITE_ORE.get())
			.add(BlockInit.OBSIDIAN_LAGOMITE_ORE.get());
		tag(Tags.Blocks.SANDS)
			.add(BlockInit.BLACK_SAND.get())
			.add(BlockInit.DEEP_SAND.get())
			.add(BlockInit.LEADED_QUARTZ_SAND.get());
		tag(Tags.Blocks.STORAGE_BLOCKS)
			.addTag(AlloysTags.Blocks.SMELTED_STORAGE_BLOCK)
			.addTag(AlloysTags.Blocks.RAW_STORAGE_BLOCK);
		tag(Tags.Blocks.ORES)
			.addTag(AlloysTags.Blocks.SOPHIE_ORES_BLOCK);

		tag(Tags.Blocks.COBBLESTONES)
			.add(BlockInit.COBBLED_CALCITE.get())
			.add(BlockInit.COBBLED_GRANITE.get())
			.add(BlockInit.COBBLED_BLACKSTONE.get())
			.add(BlockInit.COBBLED_DIORITE.get())
			.add(BlockInit.SOUL_COBBLESTONE.get())
			.add(BlockInit.MOSSY_COBBLED_DEEPSLATE.get());


		tag(Tags.Blocks.GLASS_BLOCKS_TINTED)
			.addTag(AlloysTags.Blocks.LEADED_QUARTZ_GLASS_BLOCK);
		tag(Tags.Blocks.GLASS_BLOCKS_COLORLESS)
			.add(BlockInit.LEADED_GLASS.get());
		tag(Tags.Blocks.GLASS_BLOCKS)
			.addTag(AlloysTags.Blocks.LEADED_QUARTZ_GLASS_BLOCK);
		tag(Tags.Blocks.GLASS_PANES_COLORLESS)
			.add(BlockInit.LEADED_GLASS_PANE.get());
		tag(Tags.Blocks.GLASS_PANES)
			.addTag(AlloysTags.Blocks.LEADED_QUARTZ_GLASS_PANES_BLOCK);

		tag(Tags.Blocks.ORES_IN_GROUND_DEEPSLATE)
			.add(BlockInit.DEEPSLATE_SILVER_ORE.get())
			.add(BlockInit.DEEPSLATE_TUNGSTEN_ORE.get())
			.add(BlockInit.DEEPSLATE_ELECTRUM_ORE.get())
			.add(BlockInit.DEEPSLATE_MEAT_ORE.get())
			.add(BlockInit.DEEPSLATE_LEAD_ORE.get())
			.add(BlockInit.DEEPSLATE_FOXITE_ORE.get())
			.add(BlockInit.DEEPSLATE_TRITONIUM_ORE.get())
			.add(BlockInit.DEEPSLATE_JADE_ORE.get())
			.add(BlockInit.DEEPSLATE_QUINGUM_ORE.get());
		tag(Tags.Blocks.ORES_IN_GROUND_STONE)
			.add(BlockInit.SILVER_ORE.get())
			.add(BlockInit.TUNGSTEN_ORE.get())
			.add(BlockInit.ELECTRUM_ORE.get())
			.add(BlockInit.MEAT_ORE.get())
			.add(BlockInit.LEAD_ORE.get())
			.add(BlockInit.FOXITE_ORE.get())
			.add(BlockInit.TRITONIUM_ORE.get())
			.add(BlockInit.JADE_ORE.get())
			.add(BlockInit.QUINGUM_ORE.get());
		tag(Tags.Blocks.ORES_IN_GROUND_NETHERRACK)
			.add(BlockInit.NETHER_MEAT_ORE.get())
			.add(BlockInit.NETHER_FOXITE_ORE.get())
			.add(BlockInit.NETHER_MITHRIL_ORE.get())
			.add(BlockInit.CRIMSON_COAL_ORE.get());
		tag(AlloysTags.Blocks.C_ORES_IN_GROUND_BASALT_BLOCK)
			.add(BlockInit.BASALT_MITHRIL_ORE.get());
		tag(AlloysTags.Blocks.C_ORES_IN_GROUND_BLACKSTONE_BLOCK)
			.add(BlockInit.BLACKSTONE_MITHRIL_ORE.get());
		tag(AlloysTags.Blocks.C_ORES_IN_GROUND_SOUL_BLOCK)
			.add(BlockInit.SOUL_FOXITE_ORE.get())
			.add(BlockInit.SOUL_MEAT_ORE.get())
			.add(BlockInit.SOUL_MITHRIL_ORE.get());
		tag(AlloysTags.Blocks.C_ORES_IN_GROUND_OBSIDIAN_BLOCK)
			.add(BlockInit.OBSIDIAN_LAGOMITE_ORE.get());

		tag(Tags.Blocks.ORE_BEARING_GROUND_DEEPSLATE)
			.add(BlockInit.DEEPSLATE_SILVER_ORE.get())
			.add(BlockInit.DEEPSLATE_TUNGSTEN_ORE.get())
			.add(BlockInit.DEEPSLATE_ELECTRUM_ORE.get())
			.add(BlockInit.DEEPSLATE_MEAT_ORE.get())
			.add(BlockInit.DEEPSLATE_LEAD_ORE.get())
			.add(BlockInit.DEEPSLATE_FOXITE_ORE.get())
			.add(BlockInit.DEEPSLATE_TRITONIUM_ORE.get())
			.add(BlockInit.DEEPSLATE_JADE_ORE.get())
			.add(BlockInit.DEEPSLATE_QUINGUM_ORE.get());
		tag(Tags.Blocks.ORE_BEARING_GROUND_STONE)
			.add(BlockInit.SILVER_ORE.get())
			.add(BlockInit.TUNGSTEN_ORE.get())
			.add(BlockInit.ELECTRUM_ORE.get())
			.add(BlockInit.MEAT_ORE.get())
			.add(BlockInit.LEAD_ORE.get())
			.add(BlockInit.FOXITE_ORE.get())
			.add(BlockInit.TRITONIUM_ORE.get())
			.add(BlockInit.JADE_ORE.get())
			.add(BlockInit.QUINGUM_ORE.get());
		tag(Tags.Blocks.ORE_BEARING_GROUND_NETHERRACK)
			.add(BlockInit.NETHER_MEAT_ORE.get())
			.add(BlockInit.NETHER_FOXITE_ORE.get())
			.add(BlockInit.NETHER_MITHRIL_ORE.get())
			.add(BlockInit.CRIMSON_COAL_ORE.get());
		tag(AlloysTags.Blocks.C_ORE_BEARING_GROUND_BASALT_BLOCK)
			.add(BlockInit.BASALT_MITHRIL_ORE.get());
		tag(AlloysTags.Blocks.C_ORE_BEARING_GROUND_BLACKSTONE_BLOCK)
			.add(BlockInit.BLACKSTONE_MITHRIL_ORE.get());
		tag(AlloysTags.Blocks.C_ORE_BEARING_GROUND_SOUL_BLOCK)
			.add(BlockInit.SOUL_FOXITE_ORE.get())
			.add(BlockInit.SOUL_MEAT_ORE.get())
			.add(BlockInit.SOUL_MITHRIL_ORE.get());
		tag(AlloysTags.Blocks.C_ORE_BEARING_GROUND_OBSIDIAN_BLOCK)
			.add(BlockInit.OBSIDIAN_LAGOMITE_ORE.get());


		tag(AlloysTags.Blocks.C_ORES_CRIMSON_COAL_BLOCK)
			.add(BlockInit.CRIMSON_COAL_ORE.get());
		tag(AlloysTags.Blocks.C_ORES_ELECTRUM_BLOCK)
			.add(BlockInit.ELECTRUM_ORE.get())
			.add(BlockInit.DEEPSLATE_ELECTRUM_ORE.get());
		tag(AlloysTags.Blocks.C_ORES_FOXITE_BLOCK)
			.add(BlockInit.FOXITE_ORE.get())
			.add(BlockInit.DEEPSLATE_FOXITE_ORE.get())
			.add(BlockInit.NETHER_FOXITE_ORE.get());
		tag(AlloysTags.Blocks.C_ORES_JADE_BLOCK)
			.add(BlockInit.JADE_ORE.get())
			.add(BlockInit.DEEPSLATE_JADE_ORE.get());
		tag(AlloysTags.Blocks.C_ORES_LAGOMITE_BLOCK)
			.add(BlockInit.END_LAGOMITE_ORE.get())
			.add(BlockInit.OBSIDIAN_LAGOMITE_ORE.get());
		tag(AlloysTags.Blocks.C_ORES_LEAD_BLOCK)
			.add(BlockInit.LEAD_ORE.get())
			.add(BlockInit.DEEPSLATE_LEAD_ORE.get());
		tag(AlloysTags.Blocks.C_ORES_MEAT_BLOCK)
			.add(BlockInit.MEAT_ORE.get())
			.add(BlockInit.DEEPSLATE_MEAT_ORE.get())
			.add(BlockInit.NETHER_MEAT_ORE.get())
			.add(BlockInit.SOUL_MEAT_ORE.get())
			.add(BlockInit.END_MEAT_ORE.get());
		tag(AlloysTags.Blocks.C_ORES_MITHRIL_BLOCK)
			.add(BlockInit.BASALT_MITHRIL_ORE.get())
			.add(BlockInit.BLACKSTONE_MITHRIL_ORE.get())
			.add(BlockInit.DEEPSLATE_MEAT_ORE.get())
			.add(BlockInit.NETHER_MITHRIL_ORE.get())
			.add(BlockInit.SOUL_MITHRIL_ORE.get())
			.add(BlockInit.END_MEAT_ORE.get());
		tag(AlloysTags.Blocks.C_ORES_QUINGUM_BLOCK)
			.add(BlockInit.QUINGUM_ORE.get())
			.add(BlockInit.DEEPSLATE_QUINGUM_ORE.get());
		tag(AlloysTags.Blocks.C_ORES_SILVER_BLOCK)
			.add(BlockInit.SILVER_ORE.get())
			.add(BlockInit.DEEPSLATE_SILVER_ORE.get());
		tag(AlloysTags.Blocks.C_ORES_TRITONIUM_BLOCK)
			.add(BlockInit.TRITONIUM_ORE.get())
			.add(BlockInit.DEEPSLATE_TRITONIUM_ORE.get());
		tag(AlloysTags.Blocks.C_ORES_TUNGSTEN_BLOCK)
			.add(BlockInit.TUNGSTEN_ORE.get())
			.add(BlockInit.DEEPSLATE_TUNGSTEN_ORE.get())
			.add(BlockInit.END_TUNGSTEN_ORE.get());
		
		tag(AlloysTags.Blocks.C_STORAGE_BABULYMN_BLOCK)
			.add(BlockInit.BABULYMN_BLOCK.get());
		tag(AlloysTags.Blocks.C_STORAGE_CRIMSON_COAL_BLOCK)
			.add(BlockInit.CRIMSON_COAL_BLOCK.get());
		tag(AlloysTags.Blocks.C_STORAGE_ELECTRUM_BLOCK)
			.add(BlockInit.ELECTRUM_BLOCK.get());
		tag(AlloysTags.Blocks.C_STORAGE_FOXITE_BLOCK)
			.add(BlockInit.FOXITE_BLOCK.get());
		tag(AlloysTags.Blocks.C_STORAGE_JADE_BLOCK)
			.add(BlockInit.JADE_BLOCK.get());
		tag(AlloysTags.Blocks.C_STORAGE_LAGOMITE_BLOCK)
			.add(BlockInit.LAGOMITE_BLOCK.get());
		tag(AlloysTags.Blocks.C_STORAGE_LEAD_BLOCK)
			.add(BlockInit.LEAD_BLOCK.get());
		tag(AlloysTags.Blocks.C_STORAGE_LYCALITE_BLOCK)
			.add(BlockInit.LYCALITE_BLOCK.get());
		tag(AlloysTags.Blocks.C_STORAGE_MEAT_BLOCK)
			.add(BlockInit.MEAT_BLOCK.get());
		tag(AlloysTags.Blocks.C_STORAGE_MITHRIL_BLOCK)
			.add(BlockInit.MITHRIL_BLOCK.get());
		tag(AlloysTags.Blocks.C_STORAGE_OBERITE_BLOCK)
			.add(BlockInit.OBERITE_BLOCK.get());
		tag(AlloysTags.Blocks.C_STORAGE_QUINGUM_BLOCK)
			.add(BlockInit.QUINGUM_BLOCK.get());
		tag(AlloysTags.Blocks.C_STORAGE_SILVER_BLOCK)
			.add(BlockInit.SILVER_BLOCK.get());
		tag(AlloysTags.Blocks.C_STORAGE_STEEL_BLOCK)
			.add(BlockInit.STEEL_BLOCK.get());
		tag(AlloysTags.Blocks.C_STORAGE_TRITONIUM_BLOCK)
			.add(BlockInit.TRITONIUM_BLOCK.get());
		tag(AlloysTags.Blocks.C_STORAGE_TUNGSTEN_BLOCK)
			.add(BlockInit.TUNGSTEN_BLOCK.get());
		tag(AlloysTags.Blocks.C_STORAGE_ELECTRUM_RAW_BLOCK)
			.add(BlockInit.RAW_ELECTRUM_BLOCK.get());
		tag(AlloysTags.Blocks.C_STORAGE_FOXITE_RAW_BLOCK)
			.add(BlockInit.RAW_FOXITE_BLOCK.get());
		tag(AlloysTags.Blocks.C_STORAGE_LAGOMITE_RAW_BLOCK)
			.add(BlockInit.RAW_LAGOMITE_BLOCK.get());
		tag(AlloysTags.Blocks.C_STORAGE_LEAD_RAW_BLOCK)
			.add(BlockInit.RAW_LEAD_BLOCK.get());
		tag(AlloysTags.Blocks.C_STORAGE_MITHRIL_RAW_BLOCK)
			.add(BlockInit.RAW_MITHRIL_BLOCK.get());
		tag(AlloysTags.Blocks.C_STORAGE_SILVER_RAW_BLOCK)
			.add(BlockInit.RAW_SILVER_BLOCK.get());
		tag(AlloysTags.Blocks.C_STORAGE_TRITONIUM_RAW_BLOCK)
			.add(BlockInit.RAW_TRITONIUM_BLOCK.get());
		tag(AlloysTags.Blocks.C_STORAGE_TUNGSTEN_RAW_BLOCK)
			.add(BlockInit.RAW_TUNGSTEN_BLOCK.get());


	//Alloys Tags
		tag(AlloysTags.Blocks.SOUL_ORE_REPLACEABLES)
			.add(BlockInit.SOUL_COBBLESTONE.get())
			.add(BlockInit.SOUL_STONE.get())
			.add(Blocks.SOUL_SOIL)
			.add(Blocks.SOUL_SAND);
		tag(AlloysTags.Blocks.SOUL_GRAVEL_REPLACEABLES)
			.add(Blocks.SOUL_SAND)
			.add(Blocks.NETHERRACK)
			.add(Blocks.GRAVEL);
		tag(AlloysTags.Blocks.SLATE_REPLACEABLES)
			.add(Blocks.STONE)
			.add(Blocks.COBBLESTONE)
			.add(Blocks.DEEPSLATE)
			.add(Blocks.COBBLED_DEEPSLATE)
			.add(Blocks.DIORITE)
			.add(Blocks.GRANITE)
			.add(Blocks.ANDESITE)
			.add(Blocks.DRIPSTONE_BLOCK)
			.add(Blocks.GRAVEL)
			.add(BlockInit.DEEP_GRAVEL.get());

		tag(AlloysTags.Blocks.OREBERRY_SURVIVE)
			.addTag(BlockTags.DIRT)
			.addTag(BlockTags.SAND)
			.addTag(BlockTags.BASE_STONE_OVERWORLD)
			.addTag(Tags.Blocks.COBBLESTONES)
			.addTag(Tags.Blocks.COBBLESTONES_DEEPSLATE)
			.addTag(Tags.Blocks.STONES);



		tag(AlloysTags.Blocks.SOPHIE_ORES_BLOCK)
			.add(BlockInit.CRIMSON_COAL_ORE.get())
			.add(BlockInit.JADE_ORE.get())
			.add(BlockInit.DEEPSLATE_JADE_ORE.get())
			.add(BlockInit.QUINGUM_ORE.get())
			.add(BlockInit.DEEPSLATE_QUINGUM_ORE.get())
			.add(BlockInit.END_LAGOMITE_ORE.get())
			.add(BlockInit.OBSIDIAN_LAGOMITE_ORE.get())
			.add(BlockInit.TRITONIUM_ORE.get())
			.add(BlockInit.DEEPSLATE_TRITONIUM_ORE.get())
			.add(BlockInit.SOUL_FOXITE_ORE.get())
			.add(BlockInit.NETHER_FOXITE_ORE.get())
			.add(BlockInit.DEEPSLATE_FOXITE_ORE.get())
			.add(BlockInit.FOXITE_ORE.get())
			.add(BlockInit.SOUL_MITHRIL_ORE.get())
			.add(BlockInit.RICH_BASALT.get())
			.add(BlockInit.BASALT_MITHRIL_ORE.get())
			.add(BlockInit.BLACKSTONE_MITHRIL_ORE.get())
			.add(BlockInit.NETHER_MITHRIL_ORE.get())
			.add(BlockInit.DEEPSLATE_LEAD_ORE.get())
			.add(BlockInit.LEAD_ORE.get())
			.add(BlockInit.END_MEAT_ORE.get())
			.add(BlockInit.SOUL_MEAT_ORE.get())
			.add(BlockInit.NETHER_MEAT_ORE.get())
			.add(BlockInit.DEEPSLATE_MEAT_ORE.get())
			.add(BlockInit.MEAT_ORE.get())
			.add(BlockInit.DEEPSLATE_ELECTRUM_ORE.get())
			.add(BlockInit.ELECTRUM_ORE.get())
			.add(BlockInit.END_TUNGSTEN_ORE.get())
			.add(BlockInit.DEEPSLATE_TUNGSTEN_ORE.get())
			.add(BlockInit.TUNGSTEN_ORE.get())
			.add(BlockInit.DEEPSLATE_SILVER_ORE.get())
			.add(BlockInit.SILVER_ORE.get());

		tag(AlloysTags.Blocks.SMELTED_STORAGE_BLOCK)
			.addTag(AlloysTags.Blocks.C_STORAGE_BABULYMN_BLOCK)
			.addTag(AlloysTags.Blocks.C_STORAGE_CRIMSON_COAL_BLOCK)
			.addTag(AlloysTags.Blocks.C_STORAGE_ELECTRUM_BLOCK)
			.addTag(AlloysTags.Blocks.C_STORAGE_FOXITE_BLOCK)
			.addTag(AlloysTags.Blocks.C_STORAGE_JADE_BLOCK)
			.addTag(AlloysTags.Blocks.C_STORAGE_LAGOMITE_BLOCK)
			.addTag(AlloysTags.Blocks.C_STORAGE_LEAD_BLOCK)
			.addTag(AlloysTags.Blocks.C_STORAGE_LYCALITE_BLOCK)
			.addTag(AlloysTags.Blocks.C_STORAGE_MEAT_BLOCK)
			.addTag(AlloysTags.Blocks.C_STORAGE_MITHRIL_BLOCK)
			.addTag(AlloysTags.Blocks.C_STORAGE_OBERITE_BLOCK)
			.addTag(AlloysTags.Blocks.C_STORAGE_QUINGUM_BLOCK)
			.addTag(AlloysTags.Blocks.C_STORAGE_SILVER_BLOCK)
			.addTag(AlloysTags.Blocks.C_STORAGE_STEEL_BLOCK)
			.addTag(AlloysTags.Blocks.C_STORAGE_TRITONIUM_BLOCK)
			.addTag(AlloysTags.Blocks.C_STORAGE_TUNGSTEN_BLOCK);
		tag(AlloysTags.Blocks.RAW_STORAGE_BLOCK)
			.addTag(AlloysTags.Blocks.C_STORAGE_ELECTRUM_RAW_BLOCK)
			.addTag(AlloysTags.Blocks.C_STORAGE_FOXITE_RAW_BLOCK)
			.addTag(AlloysTags.Blocks.C_STORAGE_LAGOMITE_RAW_BLOCK)
			.addTag(AlloysTags.Blocks.C_STORAGE_LEAD_RAW_BLOCK)
			.addTag(AlloysTags.Blocks.C_STORAGE_MITHRIL_RAW_BLOCK)
			.addTag(AlloysTags.Blocks.C_STORAGE_SILVER_RAW_BLOCK)
			.addTag(AlloysTags.Blocks.C_STORAGE_TRITONIUM_RAW_BLOCK)
			.addTag(AlloysTags.Blocks.C_STORAGE_TUNGSTEN_RAW_BLOCK);

		tag(AlloysTags.Blocks.SOUL_STONE_ALL_BLOCK)
			.add(BlockInit.SOUL_STONE.get())
			.add(BlockInit.SOUL_STONE_SLAB.get())
			.add(BlockInit.SOUL_STONE_WALL.get())
			.add(BlockInit.SOUL_STONE_STAIRS.get())
			.add(BlockInit.SOUL_STONE_BRICKS.get())
			.add(BlockInit.SOUL_STONE_BRICK_SLAB.get())
			.add(BlockInit.SOUL_STONE_BRICK_WALL.get())
			.add(BlockInit.SOUL_STONE_BRICK_STAIRS.get())
			.add(BlockInit.SOUL_STONE_BRICK_CRACKED.get())
			.add(BlockInit.SOUL_STONE_TILES.get())
			.add(BlockInit.SOUL_STONE_TILES_SLAB.get())
			.add(BlockInit.SOUL_STONE_TILES_WALL.get())
			.add(BlockInit.SOUL_STONE_TILES_STAIRS.get())
			.add(BlockInit.SOUL_STONE_TILES_CRACKED.get())
			.add(BlockInit.SOUL_COBBLESTONE.get())
			.add(BlockInit.SOUL_COBBLESTONE_SLAB.get())
			.add(BlockInit.SOUL_COBBLESTONE_WALL.get())
			.add(BlockInit.SOUL_COBBLESTONE_STAIRS.get());
		tag(AlloysTags.Blocks.BLACKSTONE_ALL_BLOCK)
			.add(Blocks.BLACKSTONE)
			.add(Blocks.BLACKSTONE_SLAB)
			.add(Blocks.BLACKSTONE_WALL)
			.add(Blocks.BLACKSTONE_STAIRS)
			.add(Blocks.POLISHED_BLACKSTONE)
			.add(Blocks.POLISHED_BLACKSTONE_SLAB)
			.add(Blocks.POLISHED_BLACKSTONE_WALL)
			.add(Blocks.POLISHED_BLACKSTONE_STAIRS)
			.add(Blocks.CHISELED_POLISHED_BLACKSTONE)
			.add(Blocks.POLISHED_BLACKSTONE_BRICKS)
			.add(Blocks.POLISHED_BLACKSTONE_BRICK_SLAB)
			.add(Blocks.POLISHED_BLACKSTONE_BRICK_WALL)
			.add(Blocks.POLISHED_BLACKSTONE_BRICK_STAIRS)
			.add(Blocks.CRACKED_POLISHED_BLACKSTONE_BRICKS)
			.add(BlockInit.COBBLED_BLACKSTONE.get())
			.add(BlockInit.COBBLED_BLACKSTONE_SLAB.get())
			.add(BlockInit.COBBLED_BLACKSTONE_WALL.get())
			.add(BlockInit.COBBLED_BLACKSTONE_STAIRS.get());
		tag(AlloysTags.Blocks.CALCITE_ALL_BLOCK)
			.add(Blocks.CALCITE)
			.add(BlockInit.COBBLED_CALCITE.get())
			.add(BlockInit.COBBLED_CALCITE_SLAB.get())
			.add(BlockInit.COBBLED_CALCITE_WALL.get())
			.add(BlockInit.COBBLED_CALCITE_STAIRS.get());
		tag(AlloysTags.Blocks.DIORITE_ALL_BLOCK)
			.add(Blocks.DIORITE)
			.add(Blocks.DIORITE_SLAB)
			.add(Blocks.DIORITE_WALL)
			.add(Blocks.DIORITE_STAIRS)
			.add(Blocks.POLISHED_DIORITE)
			.add(Blocks.POLISHED_DIORITE_SLAB)
			.add(Blocks.POLISHED_DIORITE_STAIRS)
			.add(BlockInit.COBBLED_DIORITE.get())
			.add(BlockInit.COBBLED_DIORITE_SLAB.get())
			.add(BlockInit.COBBLED_DIORITE_WALL.get())
			.add(BlockInit.COBBLED_DIORITE_STAIRS.get());
		tag(AlloysTags.Blocks.GRANITE_ALL_BLOCK)
			.add(Blocks.GRANITE)
			.add(Blocks.GRANITE_SLAB)
			.add(Blocks.GRANITE_WALL)
			.add(Blocks.GRANITE_STAIRS)
			.add(Blocks.POLISHED_GRANITE)
			.add(Blocks.POLISHED_GRANITE_SLAB)
			.add(Blocks.POLISHED_GRANITE_STAIRS)
			.add(BlockInit.COBBLED_GRANITE.get())
			.add(BlockInit.COBBLED_GRANITE_SLAB.get())
			.add(BlockInit.COBBLED_GRANITE_WALL.get())
			.add(BlockInit.COBBLED_GRANITE_STAIRS.get());
		tag(AlloysTags.Blocks.SLATE_ALL_BLOCK)
			.add(BlockInit.SLATE.get())
			.add(BlockInit.SLATE_SLAB.get())
			.add(BlockInit.SLATE_WALL.get())
			.add(BlockInit.SLATE_STAIRS.get())
			.add(BlockInit.SLATE_BRICKS.get())
			.add(BlockInit.SLATE_BRICK_SLAB.get())
			.add(BlockInit.SLATE_BRICK_WALL.get())
			.add(BlockInit.SLATE_BRICK_STAIRS.get())
			.add(BlockInit.SLATE_BRICKS_CRACKED.get())
			.add(BlockInit.SLATE_TILES.get())
			.add(BlockInit.SLATE_TILE_SLAB.get())
			.add(BlockInit.SLATE_TILE_WALL.get())
			.add(BlockInit.SLATE_TILE_STAIRS.get())
			.add(BlockInit.SLATE_TILES_CRACKED.get());
		tag(AlloysTags.Blocks.MOSSY_DEEPSLATE_ALL_BLOCK)
			.add(BlockInit.MOSSY_COBBLED_DEEPSLATE.get())
			.add(BlockInit.MOSSY_COBBLED_DEEPSLATE_SLAB.get())
			.add(BlockInit.MOSSY_COBBLED_DEEPSLATE_WALL.get())
			.add(BlockInit.MOSSY_COBBLED_DEEPSLATE_STAIRS.get())
			.add(BlockInit.MOSSY_DEEPSLATE_BRICKS.get())
			.add(BlockInit.MOSSY_DEEPSLATE_BRICK_SLAB.get())
			.add(BlockInit.MOSSY_DEEPSLATE_BRICK_WALL.get())
			.add(BlockInit.MOSSY_DEEPSLATE_BRICK_STAIRS.get());

		tag(AlloysTags.Blocks.DUSTY_LAMPS_BLOCK)
			.addTag(AlloysTags.Blocks.LAMPS_WEAK_BLOCK)
			.addTag(AlloysTags.Blocks.LAMPS_MEDIUM_BLOCK)
			.addTag(AlloysTags.Blocks.LAMPS_STRONG_BLOCK)
			.addTag(AlloysTags.Blocks.LAMPS_VERY_STRONG_BLOCK);
		tag(AlloysTags.Blocks.LAMPS_WEAK_BLOCK)
			.add(BlockInit.DUSTY_COAL_LAMP.get())
			.add(BlockInit.DUSTY_CRIMSON_LAMP.get())
			.add(BlockInit.DUSTY_FOXITE_LAMP.get())
			.add(BlockInit.DUSTY_IRON_LAMP.get())
			.add(BlockInit.DUSTY_LAPIS_LAMP.get())
			.add(BlockInit.DUSTY_LYCALITE_LAMP.get())
			.add(BlockInit.DUSTY_NETHERITE_LAMP.get())
			.add(BlockInit.DUSTY_ZINC_LAMP.get());
		tag(AlloysTags.Blocks.LAMPS_MEDIUM_BLOCK)
			.add(BlockInit.DUSTY_JADE_LAMP.get())
			.add(BlockInit.DUSTY_LAMP.get())
			.add(BlockInit.DUSTY_OBERITE_LAMP.get())
			.add(BlockInit.DUSTY_STEEL_LAMP.get())
			.add(BlockInit.DUSTY_BRASS_LAMP.get());
		tag(AlloysTags.Blocks.LAMPS_STRONG_BLOCK)
			.add(BlockInit.DUSTY_AMETHYST_LAMP.get())
			.add(BlockInit.DUSTY_COPPER_LAMP.get())
			.add(BlockInit.DUSTY_DIAMOND_LAMP.get())
			.add(BlockInit.DUSTY_ELECTRUM_LAMP.get())
			.add(BlockInit.DUSTY_EMERALD_LAMP.get())
			.add(BlockInit.DUSTY_LEADED_QUARTZ_LAMP.get())
			.add(BlockInit.DUSTY_MITHRIL_LAMP.get())
			.add(BlockInit.DUSTY_SILVER_LAMP.get())
			.add(BlockInit.DUSTY_TUNGSTEN_LAMP.get());
		tag(AlloysTags.Blocks.LAMPS_VERY_STRONG_BLOCK)
			.add(BlockInit.DUSTY_GOLD_LAMP.get())
			.add(BlockInit.DUSTY_QUARTZ_LAMP.get())
			.add(BlockInit.DUSTY_TRITONIUM_LAMP.get());


		tag(AlloysTags.Blocks.LEADED_QUARTZ_GLASS_BLOCK)
			.add(BlockInit.LEADED_GLASS.get())
			.addTag(AlloysTags.Blocks.STAINED_LEADED_QUARTZ_GLASS_BLOCK);
		tag(AlloysTags.Blocks.STAINED_LEADED_QUARTZ_GLASS_BLOCK)
			.add(BlockInit.RED_LEADED_GLASS.get())
			.add(BlockInit.ORANGE_LEADED_GLASS.get())
			.add(BlockInit.YELLOW_LEADED_GLASS.get())
			.add(BlockInit.LIME_LEADED_GLASS.get())
			.add(BlockInit.GREEN_LEADED_GLASS.get())
			.add(BlockInit.CYAN_LEADED_GLASS.get())
			.add(BlockInit.LIGHT_BLUE_LEADED_GLASS.get())
			.add(BlockInit.BLUE_LEADED_GLASS.get())
			.add(BlockInit.PURPLE_LEADED_GLASS.get())
			.add(BlockInit.MAGENTA_LEADED_GLASS.get())
			.add(BlockInit.PINK_LEADED_GLASS.get())
			.add(BlockInit.WHITE_LEADED_GLASS.get())
			.add(BlockInit.LIGHT_GRAY_LEADED_GLASS.get())
			.add(BlockInit.GRAY_LEADED_GLASS.get())
			.add(BlockInit.BLACK_LEADED_GLASS.get())
			.add(BlockInit.BROWN_LEADED_GLASS.get());

		tag(AlloysTags.Blocks.LEADED_QUARTZ_GLASS_PANES_BLOCK)
			.add(BlockInit.LEADED_GLASS_PANE.get())
			.addTag(AlloysTags.Blocks.STAINED_LEADED_QUARTZ_GLASS_PANES_BLOCK);
		tag(AlloysTags.Blocks.STAINED_LEADED_QUARTZ_GLASS_PANES_BLOCK)
			.add(BlockInit.RED_LEADED_GLASS_PANE.get())
			.add(BlockInit.ORANGE_LEADED_GLASS_PANE.get())
			.add(BlockInit.YELLOW_LEADED_GLASS_PANE.get())
			.add(BlockInit.LIME_LEADED_GLASS_PANE.get())
			.add(BlockInit.GREEN_LEADED_GLASS_PANE.get())
			.add(BlockInit.CYAN_LEADED_GLASS_PANE.get())
			.add(BlockInit.LIGHT_BLUE_LEADED_GLASS_PANE.get())
			.add(BlockInit.BLUE_LEADED_GLASS_PANE.get())
			.add(BlockInit.PURPLE_LEADED_GLASS_PANE.get())
			.add(BlockInit.MAGENTA_LEADED_GLASS_PANE.get())
			.add(BlockInit.PINK_LEADED_GLASS_PANE.get())
			.add(BlockInit.WHITE_LEADED_GLASS_PANE.get())
			.add(BlockInit.LIGHT_GRAY_LEADED_GLASS_PANE.get())
			.add(BlockInit.GRAY_LEADED_GLASS_PANE.get())
			.add(BlockInit.BLACK_LEADED_GLASS_PANE.get())
			.add(BlockInit.BROWN_LEADED_GLASS_PANE.get());

		tag(AlloysTags.Blocks.C_LANTERNS_BLOCK)
			.add(Blocks.LANTERN)
			.add(BlockInit.FOXITE_LANTERN.get())
			.add(BlockInit.NETHERITE_LANTERN.get())
			.add(BlockInit.SILVER_LANTERN.get())
			.add(BlockInit.TRITONIUM_LANTERN.get())
			.add(BlockInit.TUNGSTEN_LANTERN.get());
		tag(AlloysTags.Blocks.C_SOUL_LANTERNS_BLOCK)
			.add(Blocks.SOUL_LANTERN)
			.add(BlockInit.FOXITE_SOUL_LANTERN.get())
			.add(BlockInit.NETHERITE_SOUL_LANTERN.get())
			.add(BlockInit.SILVER_SOUL_LANTERN.get())
			.add(BlockInit.TRITONIUM_SOUL_LANTERN.get())
			.add(BlockInit.TUNGSTEN_SOUL_LANTERN.get());
		tag(AlloysTags.Blocks.C_BARS_BLOCK)
			.add(Blocks.IRON_BARS)
			.add(BlockInit.FOXITE_BARS.get())
			.add(BlockInit.LEAD_BARS.get())
			.add(BlockInit.SILVER_BARS.get())
			.add(BlockInit.TRITONIUM_BARS.get());
		tag(Tags.Blocks.CHAINS)
			.add(Blocks.CHAIN)
			.add(BlockInit.FOXITE_CHAIN.get())
			.add(BlockInit.NETHERITE_CHAIN.get())
			.add(BlockInit.SILVER_CHAIN.get())
			.add(BlockInit.TRITONIUM_CHAIN.get())
			.add(BlockInit.TUNGSTEN_CHAIN.get());

	//Special Tags
		tag(AlloysTags.Blocks.FARMERS_COMPOST_ACTIVATOR)
			.addTag(AlloysTags.Blocks.C_ORES_JADE_BLOCK)
			.addTag(AlloysTags.Blocks.C_STORAGE_JADE_BLOCK)
			.add(BlockInit.DUSTY_JADE_LAMP.get());

		tag(AlloysTags.Blocks.CREATE_WRENCH_PICKUP)
			.addTag(AlloysTags.Blocks.C_LANTERNS_BLOCK)
			.addTag(AlloysTags.Blocks.C_SOUL_LANTERNS_BLOCK)
			.addTag(AlloysTags.Blocks.DUSTY_LAMPS_BLOCK)
			.addTag(Tags.Blocks.CHAINS);
		tag(AlloysTags.Blocks.CREATE_FAN_TRANSPARENT)
			.addTag(Tags.Blocks.CHAINS)
			.addTag(AlloysTags.Blocks.C_BARS_BLOCK)
			.addTag(AlloysTags.Blocks.C_LANTERNS_BLOCK)
			.addTag(AlloysTags.Blocks.C_SOUL_LANTERNS_BLOCK);
		tag(AlloysTags.Blocks.CREATE_HAUNTING_CATALYST)
			.addTag(AlloysTags.Blocks.C_SOUL_LANTERNS_BLOCK);

	}
	private static ResourceLocation internal(String path) {
		return ResourceLocation.fromNamespaceAndPath(SophiesAlloys.MOD_ID, path);
	}
}
