modLoader="javafml" 
loaderVersion="${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/Bentcheesee/SophiesAlloys/issues"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId="sophies_alloys"
version="1.1.0"
displayName="Sophie's Alloys"
logoFile="sophiesalloys.png"
credits="Bentcheesee, developer; Dkurodraws, secondary texture artist; No-Zombie9031, reddit's number 1 painting enthusiest"
authors="Bentcheesee"
description='''A very poorly made mod designed to revamp Minecraft's tool progression and expand Create's automation systems'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.

[[dependencies.sophies_alloys]]
	modId="forge"
	mandatory=true
	versionRange="${forge_version_range}"
	# An ordering relationship for the dependency - BEFORE or AFTER required if the dependency is not mandatory
	# BEFORE or AFTER- This mod is loaded BEFORE or AFTER the dependency
	ordering="AFTER"
	# Side this dependency is applied on - BOTH, CLIENT, or SERVER
	side="BOTH"

[[dependencies.sophies_alloys]]
	modId="minecraft"
	mandatory=true
	versionRange="1.19.2"
	ordering="AFTER"
	side="BOTH"
[[dependencies.sophies_alloys]]
	modId="create"
	mandatory=true
	versionRange="1.19.2"
	ordering="AFTER"
	side="BOTH"
[[dependencies.sophies_alloys]]
	modId="create_dd"
	mandatory=false
	versionRange="1.19.2"
	ordering="AFTER"
	side="BOTH"
[[dependencies.sophies_alloys]]
	modId="farmersdelight"
	mandatory=false
	versionRange="1.19.2"
	ordering="AFTER"
	side="BOTH"