
modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}"
license="SophieLicense"
issueTrackerURL="https://github.com/Bentcheesee/BetterTables/issues"

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

modId="sophies_alloys"
version="2.0.0 Beta 2"
displayName="Sophie's Alloys"

logoFile= "../sophiesalloys.png"
authors='''
Bentcheesee
'''
credits='''
Anyone who has provided code, PRs, Issues, or otherwise to the github
'''
description='''
A very poorly made mod designed to revamp Minecraft's tool progression and expand Create's automation systems.
'''

# The [[mixins]] block allows you to declare your mixin config to FML so that it gets loaded.
#[[mixins]]
#config="${mod_id}.mixins.json"

# The [[accessTransformers]] block allows you to declare where your AT file is.
# If this block is omitted, a fallback attempt will be made to load an AT from META-INF/accesstransformer.cfg
#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

# The coremods config file path is not configurable and is always loaded from META-INF/coremods.json

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.sophies_alloys]] #optional
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="[${neo_version},)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.sophies_alloys]]
	modId="minecraft"
	type="required"
	versionRange="${minecraft_version_range}"
	ordering="AFTER"
	side="BOTH"

[[dependencies.sophies_alloys]]
	modId="create"
	type="required"
	versionRange="${minecraft_version_range}"
	ordering="AFTER"
	side="BOTH"
